INSERT INTO roles (name) VALUES ('admin');
INSERT INTO roles (name) VALUES ('employee');
INSERT INTO roles (name) VALUES ('manager');
INSERT INTO roles (name) VALUES ('member');

 
INSERT INTO characteristics (name) VALUES ('Java');
INSERT INTO characteristics (name) VALUES ('Python');
INSERT INTO characteristics (name) VALUES ('JavaScript');
INSERT INTO characteristics (name) VALUES ('C++');
INSERT INTO characteristics (name) VALUES ('HTML');
INSERT INTO characteristics (name) VALUES ('CSS');
INSERT INTO characteristics (name) VALUES ('SQL');
INSERT INTO characteristics (name) VALUES ('React');
INSERT INTO characteristics (name) VALUES ('Angular');
INSERT INTO characteristics (name) VALUES ('Node.js');
INSERT INTO characteristics (name) VALUES ('Kotlin');
INSERT INTO characteristics (name) VALUES ('PHP');
INSERT INTO characteristics (name) VALUES ('ASP.NET');

INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Backend API Development for E-commerce Platform', 'Build a robust backend API for the e-commerce platform to handle user authentication, product management, and order processing.', '2024-02-10', '2030-06-10', 5, 1);
INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Frontend UI Design for Cybersecurity Dashboard', 'Design an intuitive and responsive user interface for the cybersecurity dashboard, focusing on usability and data visualization.', '2024-01-15', '2030-07-15', 5, 1);
INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Full Stack Development for Cloud-based Application', 'Develop a full stack application leveraging cloud services, with emphasis on both frontend user experience and backend scalability.', '2024-03-20', '2030-08-20', 5, 1);
INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Mobile App Backend Infrastructure Setup', 'Set up the backend infrastructure for a mobile application, including API endpoints, database management, and server configurations.', '2024-04-25', '2030-09-25', 5, 1);
INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Frontend Development for Data Analytics Dashboard', 'Implement frontend components for a data analytics dashboard, focusing on interactive data visualization and user-friendly design.', '2024-01-30', '2030-10-30', 5, 1);
INSERT INTO projects (name, description, start_date, finish_date, vacancies, is_active) VALUES ('Backend Integration of AI Models', 'Integrate AI models into the backend infrastructure, enabling predictive analytics and intelligent automation.', '2024-02-05', '2030-11-05', 5, 1);

INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES ('Laura', 'Jimenez', 'MPT000001', 'laura.jimenez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 1);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES ('Juan', 'Perez', 'MPT000002', 'juan.perez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('María', 'González', 'MPT000003', 'maria.gonzalez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Carlos', 'Rodriguez', 'MPT000004', 'carlos.rodriguez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Ana', 'Martinez', 'MPT000005', 'ana.martinez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 0, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Pedro', 'Sánchez', 'MPT000006', 'pedro.sanchez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Sofía', 'Lopez', 'MPT000007', 'sofia.lopez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Pablo', 'Fernandez', 'MPT000008', 'pablo.fernandez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Julia', 'Diaz', 'MPT000009', 'julia.diaz@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Miguel', 'Garcia', 'MPT000010', 'miguel.garcia@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Elena', 'Ramirez', 'MPT000011', 'elena.ramirez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Javier', 'Torres', 'MPT000012', 'javier.torres@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 0, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Paula', 'Moreno', 'MPT000013', 'paula.moreno@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('David', 'Ruiz', 'MPT000014', 'david.ruiz@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Carmen', 'Alvarez', 'MPT000015', 'carmen.alvarez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Adrián', 'Gómez', 'MPT000016', 'adrian.gomez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Silvia', 'Hernandez', 'MPT000017', 'silvia.hernandez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Alejandro', 'Muñoz', 'MPT000018', 'alejandro.munoz@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Lucia', 'Vazquez', 'MPT000019', 'lucia.vazquez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Diego', 'Iglesias', 'MPT000020', 'diego.iglesias@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Valeria', 'Santiago', 'MPT000021', 'valeria.santiago@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Guillermo', 'Ortega', 'MPT000022', 'guillermo.ortega@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 0, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Raquel', 'Jimenez', 'MPT000023', 'raquel.jimenez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Samuel', 'Perez', 'MPT000024', 'samuel.perez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Isabel', 'Gonzalez', 'MPT000025', 'isabel.gonzalez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Natalia', 'Rodriguez', 'MPT000026', 'natalia.rodriguez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Ruben', 'Martinez', 'MPT000027', 'ruben.martinez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Patricia', 'Sanchez', 'MPT000028', 'patricia.sanchez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Sara', 'Lopez', 'MPT000029', 'sara.lopez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 0, 2);
INSERT INTO users (name, last_name, das, email, password, profile_pic, cv, is_active, role_id) VALUES('Alvaro', 'Fernandez', 'MPT000030', 'alvaro.fernandez@mpt.com', 'Abcdefg1!', 'profile_pic.png', 'cv.pdf', 1, 2);

INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (1, 1, 1, '2024-05-11', '2025-06-10', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (1, 2, 1, '2024-05-13', '2025-06-01', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (1, 3, 1, '2024-08-01', '2025-06-10', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (1, 4, 1, '2024-05-11', '2025-05-12', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (1, 5, 0, '2024-12-21', '2025-06-10', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (2, 6, 1, '2024-06-15', '2027-12-15', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (2, 7, 1, '2024-08-15', '2026-12-15', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (2, 8, 1, '2024-09-15', '2024-12-15', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (2, 9, 1, '2024-06-15', '2029-12-15', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (2, 10, 1, '2024-06-15', '2024-12-15', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (3, 11, 1, '2024-07-29', '2028-12-20', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (3, 12, 0, '2024-07-21', '2025-12-20', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (3, 13, 1, '2024-09-20', '2027-12-20', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (3, 14, 1, '2024-10-26', '2027-12-20', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (3, 15, 1, '2024-07-20', '2024-12-20', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (4, 16, 1, '2024-08-25', '2025-01-25', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (4, 17, 1, '2024-09-25', '2026-01-25', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (4, 18, 1, '2024-10-25', '2025-01-25', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (4, 19, 1, '2024-08-25', '2028-01-25', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (4, 20, 1, '2024-08-25', '2028-01-25', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (5, 21, 1, '2024-09-30', '2027-02-28', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (5, 22, 0, '2024-11-30', '2026-02-20', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (5, 23, 1, '2024-10-30', '2029-02-08', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (5, 24, 1, '2024-12-30', '2028-02-27', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (5, 25, 1, '2024-09-30', '2025-02-28', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (6, 26, 1, '2024-10-05', '2025-06-05', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (6, 27, 1, '2024-10-10', '2027-03-05', 3);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (6, 28, 1, '2024-10-15', '2028-08-05', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (6, 29, 0, '2024-12-05', '2026-03-05', 4);
INSERT INTO user_projects (project_id, user_id, is_active, join_date, exit_date, role_id) VALUES (6, 30, 1, '2024-11-01', '2025-09-05', 4);

INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2024-05-15', '2024-06-15', 1, 'HIGH', 1);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2024-05-20', '2025-12-20', 1, 'MID', 1);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2024-07-01', '2024-07-01', 1, 'LOW', 1);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2024-06-10', '2026-03-10', 1, 'HIGH', 1);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2024-12-20', '2028-09-27', 1, 'MID', 1);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2024-06-15', '2024-07-19', 1, 'HIGH', 2);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2025-11-20', '2026-12-20', 1, 'MID', 2);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2025-06-01', '2027-08-01', 1, 'LOW', 2);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2026-07-10', '2028-10-15', 1, 'HIGH', 2);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2026-04-20', '2029-08-20', 1, 'MID', 2);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2024-09-15', '2027-08-05', 1, 'HIGH', 3);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2028-03-20', '2024-06-23', 1, 'MID', 3);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2026-09-01', '2028-12-01', 1, 'LOW', 3);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2027-11-10', '2026-09-13', 1, 'HIGH', 3);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2024-09-20', '2029-02-20', 1, 'MID', 3);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2024-09-15', '2025-07-15', 1, 'HIGH', 4);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2027-08-20', '2026-09-26', 1, 'MID', 4);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2028-11-01', '2027-11-01', 1, 'LOW', 4);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2029-10-10', '2027-05-04', 1, 'HIGH', 4);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2026-03-20', '2029-01-20', 1, 'MID', 4);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2024-09-15', '2027-03-11', 1, 'HIGH', 5);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2028-07-20', '2024-11-29', 1, 'MID', 5);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2025-12-01', '2025-12-01', 1, 'LOW', 5);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2027-09-10', '2024-05-16', 1, 'HIGH', 5);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2029-12-20', '2024-01-20', 1, 'MID', 5);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 1', 'Description 1', '2026-09-15', '2029-11-02', 1, 'HIGH', 6);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 2', 'Description 2', '2028-06-20', '2028-11-25', 1, 'MID', 6);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 3', 'Description 3', '2025-11-01', '2024-12-12', 1, 'LOW', 6);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 4', 'Description 4', '2029-11-10', '2026-12-09', 1, 'HIGH', 6);
INSERT INTO tasks (name, description, start_date, finish_date, is_active, priority, project_id) VALUES ('Task 5', 'Description 5', '2027-07-20', '2024-12-23', 1, 'MID', 6);

INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (1, 1, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (1, 2, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (2, 2, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (2, 5, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (2, 4, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (3, 3, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (4, 4, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (4, 1, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (4, 2, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (4, 3, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (4, 5, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (5, 5, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (5, 3, 1);
 
 
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (6, 6, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (6, 7, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (7, 7, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (7, 10, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (7, 9, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (8, 8, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (9, 9, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (9, 6, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (9, 7, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (9, 8, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (9, 10, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (10, 10, 1);
 
 
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (11, 11, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (11, 13, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (11, 15, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (12, 12, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (13, 13, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (13, 11, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (13, 12, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (14, 14, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (14, 13, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (15, 15, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (15, 11, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (15, 12, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (15, 14, 1);
 
 
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (16, 16, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (16, 18, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (16, 20, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (17, 17, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (17, 16, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (18, 18, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (18, 16, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (18, 19, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (19, 19, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (20, 20, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (20, 17, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (20, 16, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (20, 15, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (20, 18, 1);
 
 
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (21, 21, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (21, 22, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (21, 23, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (21, 24, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (22, 22, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (22, 21, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (23, 23, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (23, 24, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (23, 25, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (24, 24, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (24, 21, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (25, 25, 1);
 
 
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (26, 26, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (26, 28, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (27, 27, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (27, 27, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (27, 29, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (28, 28, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (28, 30, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (29, 29, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (29, 26, 1);
INSERT INTO user_tasks (task_id, user_id, is_active) VALUES (30, 30, 1);

INSERT INTO requests (message, project_id, user_id) VALUES ('Request message 1', 1, 1);
INSERT INTO requests (message, project_id, user_id) VALUES ('Request message 2', 2, 2);
INSERT INTO requests (message, project_id, user_id) VALUES ('Request message 3', 3, 3);
INSERT INTO requests (message, project_id, user_id) VALUES ('Request message 4', 4, 4);
INSERT INTO requests (message, project_id, user_id) VALUES ('Request message 5', 5, 5);

INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (1, 1);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (2, 1);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 1);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (7, 1);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (8, 1);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (2, 2);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 2);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (4, 2);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (8, 2);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (11, 2);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 3);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (5, 3);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (6, 3);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (8, 3);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (9, 3);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (1, 4);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 4);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (6, 4);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (7, 4);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (12, 4);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 5);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (4, 5);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (5, 5);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (10, 5);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (13, 5);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (1, 6);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (3, 6);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (7, 6);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (10, 6);
INSERT INTO project_characteristics (characteristic_id, project_id) VALUES (12, 6);

INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (1, 1);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (2, 1);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (3, 2);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (4, 2);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (5, 3);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (6, 3);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (7, 4);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (8, 4);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (9, 5);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (10, 5);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (11, 6);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (12, 6);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (13, 7);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (1, 7);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (2, 8);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (3, 8);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (4, 9);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (5, 9);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (6, 10);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (7, 10);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (8, 11);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (9, 11);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (10, 12);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (11, 12);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (12, 13);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (13, 13);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (1, 14);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (2, 14);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (3, 15);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (4, 15);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (5, 16);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (6, 16);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (7, 17);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (8, 17);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (9, 18);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (10, 18);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (11, 19);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (12, 19);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (13, 20);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (1, 20);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (2, 21);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (3, 21);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (4, 22);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (5, 22);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (6, 23);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (7, 23);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (8, 24);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (9, 24);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (10, 25);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (11, 25);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (12, 26);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (13, 26);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (1, 27);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (2, 27);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (3, 28);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (4, 28);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (5, 29);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (6, 29);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (7, 30);
INSERT INTO user_characteristics (characteristic_id, user_id) VALUES (8, 30);
